# Generated by Django 6.0.3 on 2026-03-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_image_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
