# Generated by Django 6.0.3 on 2026-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
