# Generated by Codex on 2026-04-17

import uuid

from django.db import migrations, models
from django.db.models import Q


def populate_public_ids(apps, schema_editor):
    message_model = apps.get_model("chat", "Message")
    for message in message_model.objects.filter(public_id__isnull=True):
        message.public_id = uuid.uuid4()
        message.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_is_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="client_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp", "id"]},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "receiver", "timestamp"],
                name="chat_message_sender__47eb8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "is_read", "timestamp"],
                name="chat_message_receive_7c48c9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=Q(("client_id__isnull", False)),
                fields=("sender", "client_id"),
                name="unique_sender_client_message",
            ),
        ),
        migrations.RunPython(
            code=populate_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="message",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
